sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: cl521xbb
  redis:
    host: localhost
    port: 6379
    password: cl521xbb
    database: 0
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tKuZDyvd3T8rFWxvz5q
    access-key-secret: TkdGxLQznI51eIRq4WA3BApKsVR9jI
    bucket-name: sky-itcast-hekun
  wechat:
    appid: wx3b75f96732490d12
    secret: 599aa9750d11cf660ede27fccea7e282